# Generated by Django 4.0.6 on 2022-08-01 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 1, 12, 49, 7, 71227, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 1, 12, 49, 28, 71229, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
